- alias: 'Hass Started'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: start
  action:
    - service: notify.pushbullet_isa
      data:
        title: 'Home Assistant Online'
        message: 'Online'
    - service: notify.ios_stefan_iphone_7
      data:
        message: "request_location_update"
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: "request_location_update"
    - service: python_script.device_tracker_placeholders
    - service: python_script.summary

- alias: 'Hass Ready'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    - service: notify.pushbullet_isa
      data:
        title: 'Z-wave network now ready'
        message: 'Home Assistant'

- alias: 'Hass Stopped'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: shutdown
  action:
    - service: notify.pushbullet_isa
      data:
        title: 'Home Assistant Offline'
        message: 'Offline'

- alias: Hass New Device Tracked
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.pushbullet_isa
      data:
        title: 'New device tracked'
        message: 'Look it up!'

- alias: Hass Updater
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.pushbullet_isa
      data_template: 
        title: 'New Home Assistant Release Available'
        message: "Home Assistant  {{ states.updater.updater.state }}  is now available."