- alias: Send alert when washing machine is finished
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_status
      to: Clean
      for:
        minutes: 1
    - platform: state
      entity_id: device_tracker.isabellas_iphone_6s
      to: 'home'
      for:
        minutes: 10
    - platform: state
      entity_id: device_tracker.stefan_iphone_7
      to: 'home'
      for:
        minutes: 10
    - platform: time
      at: '08:01:00'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '23:00:00'
        after: '08:00:00'
      - condition: state
        entity_id: group.persons
        state: 'home'
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Clean
      - condition: template
        value_template: >
          {% if states.automation.send_alert_when_washing_machine_is_finished.last_triggered is not none %}
            {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_when_washing_machine_is_finished.attributes.last_triggered) | int > 1800 %} true {% else %} false
            {% endif %}
          {% else %}
          false
          {% endif %}
  action:
    # - service: notify.ios_isabellas_iphone_6s
    - service_template: >
        {% if (is_state('device_tracker.isabellas_iphone_6s', 'home')) and (is_state('device_tracker.stefan_iphone_7', 'home'))  %}
          notify.all
        {% elif is_state('device_tracker.isabellas_iphone_6s', 'home') %}
          notify.ios_isabellas_iphone_6s
        {% elif is_state('device_tracker.stefan_iphone_7', 'home') %}
          notify.ios_stefan_iphone_7
        {% endif %}
      data:
        message: 'Take care of it now?'
        title: 'Washing machine is done!'
        data:
          push:
            badge: 0
            category: "WASHER"

- alias: Washer emptied
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: WASHER_EMPTIED
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Idle
    # - service: notify.all
    - service: notify.ios_isabellas_iphone_6s
      data:
        message: 'The laundry is taken care of'

- alias: Washer snoozed
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: WASHER_NOT_EMPTIED
  action:
    - delay: 0:30
    # - service: notify.ios_isabellas_iphone_6s
    - service_template: >
        {% if (is_state('device_tracker.isabellas_iphone_6s', 'home')) and (is_state('device_tracker.stefan_iphone_7', 'home'))  %}
          notify.all
        {% elif is_state('device_tracker.isabellas_iphone_6s', 'home') %}
          notify.ios_isabellas_iphone_6s
        {% elif is_state('device_tracker.stefan_iphone_7', 'home') %}
          notify.ios_stefan_iphone_7
        {% endif %}
      data:
        message: 'Take care of it now?'
        title: 'Washing machine is done!'
        data:
          push:
            badge: 0
            category: "WASHER"