homeassistant:
  customize:
    binary_sensor.switch_158d0001243520:
      friendly_name: Bed Switch 

input_boolean:
  bedside_lamp_dimmer:
    name: Dimmer Bedside Lamp
    initial: off

script:
  dim_bedside_lamp:
    sequence:
      - condition: state
        entity_id: input_boolean.bedside_lamp_dimmer
        state: 'on'
      - service: light.turn_on
        entity_id: light.bedside_lamp
        data_template:
          brightness: '{{states.light.bedside_lamp.attributes.brightness - 10}}'
      - service: script.turn_off
        entity_id: script.dim_bedside_lamp
      - service: script.turn_on
        entity_id: script.dim_bedside_lamp

  brighten_bedside_lamp:
    sequence:
    - condition: state
      entity_id: input_boolean.bedside_lamp_dimmer
      state: 'off'
    - service: light.turn_on
      entity_id: light.bedside_lamp
      data_template:
        brightness: '{{states.light.bedside_lamp.attributes.brightness + 10}}'
    - service: script.turn_off
      entity_id: script.brighten_bedside_lamp
    - service: script.turn_on
      entity_id: script.brighten_bedside_lamp


automation:
  - alias: Light Switch Bedroom Bedside Light
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001243520
        click_type: single
    action:
      service: light.toggle
      entity_id: light.bedside_lamp

  - alias: Light Switch Bedroom Ceiling Light
    initial_state: 'on'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001243520
        click_type: double
    action:
      service: light.toggle
      entity_id: light.bedroom_ceiling_light
      
  - alias: Light Bedside Lamp Window Brighten
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001243520
          click_type: long_click_press
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedside_lamp_dimmer
        state: 'off'
      - condition: state
        entity_id: light.bedside_lamp
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.brighten_bedside_lamp
        
  - alias: Light Bedside Lamp Window Brighten Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.switch_158d0001243520
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedside_lamp_dimmer
        state: 'off'
      - condition: state
        entity_id: light.bedside_lamp
        state: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedside_lamp_dimmer
        
  - alias: Light Bedside Lamp Window Dim On
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001243520
          click_type: long_click_press
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedside_lamp_dimmer
        state: 'on'
      - condition: state
        entity_id: light.bedside_lamp
        state: 'on'
    action:
      - service: script.turn_on
        entity_id: script.dim_bedside_lamp

  - alias: Light Bedside Lamp Window Dim Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.switch_158d0001243520
        from: 'on'
        to: 'off'
    condition:
      condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.bedside_lamp_dimmer
        state: 'on'
      - condition: state
        entity_id: light.bedside_lamp
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedside_lamp_dimmer

  # - alias: Light Switch Bedroom All Lights
  #   initial_state: 'on'
  #   trigger:
  #     platform: event
  #     event_type: click
  #     event_data:
  #       entity_id: binary_sensor.switch_158d0001243520
  #       click_type: long_click_press
  #   action:
  #     service: homeassistant.turn_off
  #     entity_id: group.inside_lights_automations