homeassistant:
  customize:
    input_text.lights_tiles:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 6
        # column_width: 50px
        # row_height: 50px
        # gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        color_off: '#BBBEC2'
        entities:
          - entity: script.goodnight
            # label: S1
            column: 1
            row: 1
            # row_span: 1
            # column_span: 1
            icon: mdi:hotel
          - entity: script.goodmorning
            # label: S1
            column: 2
            row: 1
            icon: mdi:kettle
          - entity: script.movie_time
            # label: S1
            column: 3
            row: 1
            icon: mdi:television-classic
    script.movie_time:
      alexa_hidden: false
      alexa_name: Movie Time
      homebridge_visible: true
      homebridge_name: Movie Time

    group.outside_lights:
      alexa_display_categories: LIGHT
      alexa_name: Outside Lights
      homebridge_visible: true
      homebridge_name: Outside Lights
      
    group.inside_lights_automations:
      alexa_name: All lights
      alexa_display_categories: LIGHT
      homebridge_visible: true
      homebridge_name: All Lights

    light.gateway_light_34ce008bfc4b:
      friendly_name: Upstairs Hallway Nightlight
      homebridge_visible: false

input_text:
  lights_tiles:
    name: Lights

script:
  movie_time:
    alias: Movie Time
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.living_room_spotlights_level, light.passage_ceiling_spotlights_level, light.upstairs_hallway_ceiling_light_level, light.kitchen_ceiling_spotlights_level, light.dining_area_ceiling_light_level, light.floorlamp_reading_light, light.floorlamp_uplight, light.isa_ceiling_light
          transition: 30
      - service: light.turn_on
        data:
          entity_id: light.living_room_ceiling_light_level, group.stairs_lights
          brightness: 10

light:
  - platform: rfxtrx
    automatic_add: true
    devices:
      # 0b11000676bc0cfe01010f70:
      #   name: Proove Dimmer
      0b11000552bc0cfe07010f70:
        name: Outside Yard Hanging Lights
  # - name: 'Stairs Bottom Spot'
  #   command_topic: milight/0x2/rgbw/1 
  #   state_topic: milight/updates/0x2/rgbw/1 
  #   <<: &MILIGHT_PARAMS
  #     platform: mqtt_json
  #     color_temp: true
  #     rgb: true
  #     brightness: true

  # - name: "Stairs Middle Spot"
  #   command_topic: milight/0x3/rgbw/1 
  #   state_topic: milight/updates/0x3/rgbw/1 
  #   <<: *MILIGHT_PARAMS

  # - name: "Stairs Top Spot"
  #   command_topic: milight/0x1/rgbw/1 
  #   state_topic: milight/updates/0x1/rgbw/1 
  #   <<: *MILIGHT_PARAMS

  - platform: lifx


group:
  lights:
    control: hidden
    name: Inside lights
    entities:
      - input_text.lights_tiles
      - group.outside_lights_card
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.dining_area_ceiling_light_level  
      - light.kitchen_ceiling_spotlights_level
      - light.floorlamp_reading_light
      - light.christmas_candelabra
      - light.storage_christmas_candelabra
      - light.floorlamp_uplight
      - light.hallway_window_light
      - light.isa_ceiling_light
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - group.stairs_lights
      - group.walk_in_closet_lights
      # - light.stefan_ceiling_light
      - light.stefan_lightstrip
      - light.upstairs_hallway_ceiling_light_level
      - light.gateway_light_34ce008bfc4b

  outside_lights_card:
    name: Outside lights
    icon: mdi:lightbulb
    entities:
      - light.outside_front_light
      - light.outside_yard_light
      - light.outside_yard_hanging_lights

# for automations, hubby doesn't like his lights to be included
  inside_lights_automations:
    name: Inside Lights Without Stefan
    entities:
      - light.bedroom_ceiling_light
      - light.bedside_lamp
      - light.living_room_ceiling_light_level
      - light.living_room_spotlights_level
      - light.passage_ceiling_spotlights_level
      - light.upstairs_hallway_ceiling_light_level
      - light.dining_area_ceiling_light_level
      - light.isa_ceiling_light
      - light.floorlamp_reading_light
      - light.floorlamp_uplight
      - light.gateway_light_34ce008bfc4b
      - light.kitchen_sink_light
      - group.stairs_lights
      - group.walk_in_closet_lights
      - light.kitchen_ceiling_spotlights_level