homeassistant:
  # customize:
  #   switch.roomba:
  #     homebridge_visible: true
  #   switch.roomba_dock:
  #     homebridge_visible: true
      
switch:
  - platform: broadlink
    friendly_name: Broadlink Hallway
    host: !secret broadlink_roomba_ip
    mac: !secret broadlink_roomba_mac
    switches:
      roomba:
        friendly_name: Roomba
        command_on: 'JgD8AGEgIV8gXyBfXCIhXyBfIAACoGIfIGAfYB9gXSIfYR5hHgACol8iHmIdYh1iXCIfYR5hHgACo2EgHmEfYR1iXCIeYh1iHQACq2AhH2EeYR9gXCMfYB9gHwAComAhH2AfYR9gXCIgYB9gHwACoWAiH2AfYB9gXCMfYB9hHgAComAhH2EeYR5hXCIgYCBfIAACoGEgIGAfYB9gXSIfYR5hHgACql8jHWIdYh1iXCMeYR5hHgACo18iHmEeYh1iXCIeYh1iHQACo18jHWIdYh5hXSIeYh1iHQACo18jHWIdYh1iXCIfYR5hHgACq18iHmEeYh1iXCIeYh1iHgANBQAAAAAAAAAAAAAAAA=='
        command_off: 'JgCQAGAhHmIfYB9gH2BdIh5iXAACbGAhHmIeYR5hH2BdIh5iXAACZGAhHmIeYR5hH2BdIh5iXAACZGEhH2AfYB9gIF9eISBgXgACYl8iIGAfYB9gH2BfICBgXgACamEhH2AfYB9gH2BfICBgXgACYmEgIGAfYCBfIF9cIx9hXAACZGAhHmIeYR5hH2BdIh5iXAANBQAAAAAAAAAA'
      roomba_dock:
        friendly_name: Roomba Dock
        command_on: 'JgA2AF8iHmIdYh1iHWJcIh5iXAACbF8iIGAeYh1iHWJeICBgXQACY18iIGAeYh1iHWJeICBgXgANBQAA'
        command_off: 'JgCQAGAhHmIfYB9gH2BdIh5iXAACbGAhHmIeYR5hH2BdIh5iXAACZGAhHmIeYR5hH2BdIh5iXAACZGEhH2AfYB9gIF9eISBgXgACYl8iIGAfYB9gH2BfICBgXgACamEhH2AfYB9gH2BfICBgXgACYmEgIGAfYCBfIF9cIx9hXAACZGAhHmIeYR5hH2BdIh5iXAANBQAAAAAAAAAA'

input_select:
  roomba_mode:
    name: Roomba
    options:
     - 'Waiting To Vacuum'
     - 'Vacuum Now'
     - 'Has Vacuumed'
     - 'Dock'
     - 'Not Today'
    initial: 'Waiting To Vacuum'
    icon: mdi:roomba

automation:
  - alias: 'Vacuum Ask When Everyone Is Away'
    trigger:
      platform: time
      minutes: 5
      seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.isabellas_iphone_6s
          state: 'not_home'
        - condition: time
          after: '09:00:00'
          before: '17:00:00'
        - condition: state
          entity_id: input_select.roomba_mode
          state: 'Waiting To Vacuum'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'Vacuum now?'
          title: 'No one seems to be at home'
          data:
            push:
              category: "vacuum"


  - alias: Vacuum Now Selected
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: VACUUM_NOW
    action:
      - service: homeassistant.turn_on
        entity_id: switch.roomba
      - service: input_select.select_option
        data:
          entity_id: input_select.roomba_mode
          option: 'Has Vacuumed'
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'Telling the Roomba to start vacuuming'

  - alias: Vacuum Snoozed Selected
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: VACUUM_LATER
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'I will check again next hour'
          title: 'Not vacuuming right now'

  - alias: Vacuum Stop Asking Selected
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: VACUUM_STOP_ASKING
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'I will check again next hour'
          title: 'Not vacuuming right now'
      - service: input_select.select_option
        data:
          entity_id: input_select.roomba_mode
          option: 'Not Today'

  ## Reset the vacuumed today check each night
  - alias: 'Vacuum Reset At Midnight'
    trigger:
      platform: time
      at: '23:59:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.roomba_mode
          option: 'Waiting To Vacuum'
      - service: homeassistant.turn_off
        entity_id: switch.roomba

  - alias: 'Vacuum Dock Roomba'
    trigger:
      platform: state
      entity_id: input_select.roomba_mode
      to: 'Dock'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.roomba
      - service: homeassistant.turn_off
        entity_id: switch.roomba_livingroom
      - delay: '0:01'
      - service: homeassistant.turn_on
        entity_id: switch.roomba_dock
      - service: homeassistant.turn_on
        entity_id: switch.roomba_dock_livingroom
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'Trying to dock Roomba'
      - service: input_select.select_option
        data:
          entity_id: input_select.roomba_mode
          option: 'Waiting To Vacuum'

  - alias: 'Vacuum Now'
    trigger:
      platform: state
      entity_id: input_select.roomba_mode
      to: 'Vacuum Now'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.roomba
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: 'Vacuuming'
      - service: input_select.select_option
        data:
          entity_id: input_select.roomba_mode
          option: 'Waiting To Vacuum'