# install:
# sudo apt-get install svtplay-dl
# custom component from:
# https://github.com/postlund/hass-config

homeassistant:
  customize:
    script.morning_news:
      homebridge_visible: true
      icon: mdi:television-classic
        

svtplay_dl:
  accounts:
    tv4play:
      username: !secret svtplay_tv4_username
      password: !secret svtplay_tv4_password

script:
  morning_news:
    alias: Morning news
    sequence:
      # tood: turn on tv with ir
      - service: script.turn_on_shield
      - service: script.svtplay_play
        data:
          entity_id: media_player.shield
          program: morning news
  
  turn_on_shield:
    alias: Turn On Livingroom Tv
    sequence:
      service: media_player.turn_on
      data:
        entity_id: media_player.shield

  svtplay_play:
    alias: Play something with svtplay_dl
    sequence:
      - service: svtplay_dl.play_url
        data_template:
          entity_id: '{{ entity_id }}'
          account: tv4play
          url: >
            {% set p = program|lower|replace(' ', '') %}
            {% if p|lower == 'masterchef' %}
              http://www.tv4play.se/feed/program/sveriges-m%C3%A4sterkock
            {% else %}
              !
            {% endif %}
          live: >
            {% set p = program|lower|replace(' ', '') %}
            {% if p|lower == 'morningnews' %}
              true
            {% else %}
              false
            {% endif %}
          title: >
            {% set p = program|lower|replace(' ', '') %}
            {% if p == 'morningnews' %}
              Nyhetsmorgon live
            {% elif p == 'masterchef' %}
              Sveriges mästerkock del
            {% else %}
              {{ program }}
            {% endif %}
      - delay: '00:00:05'  # Conditional wait until video is playing here
      - service: media_player.media_play
        data_template:
          entity_id: '{{ entity_id }}'