input_boolean:
  test:
    name: Test stuff
    initial: off

automation:
  - alias: 'Test Automation'
    initial_state: True
    trigger:
      - platform: state
        entity_id: input_boolean.test
        to: 'on'
    action:
      - service: notify.ios_isabellas_iphone_6s
        data:
          message: Fire camera motion
          data:
            attachment:
              content-type: jpeg
            push:
              category: camera
            entity_id: camera.back_door