

sensor:
  - platform: yr
    monitored_conditions:
      # - temperature
      - symbol
      - precipitation
#       - windSpeed
#       - pressure
#       - windDirection
#       - humidity
#       - fog
#       - cloudiness
#       - lowClouds
#       - mediumClouds
#       - highClouds
#       - dewpointTemperature

  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 1
      # - 2
      # - 3
      # - 4
      # - 5
      # - 6
      # - 7
    monitored_conditions:
      - summary
      - precip_probability
      - precip_type
      - precip_intensity
      - precip_intensity_max
      - temperature
  #    - dew_point
      - wind_speed
  #    - wind_bearing
    #   - cloud_cover
    #   - humidity
  #    - nearest_storm_distance
  #    - minutely_summary
      - daily_summary
      - hourly_summary
      - apparent_temperature
      - apparent_temperature_max
      - apparent_temperature_min
      - temperature_max
      - temperature_min
  #    - pressure
      - visibility
  #    - ozone

group:
  dark_sky:
    name: Dark sky
    entities:
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_apparent_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_apparent_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_max_precip_intensity
      - sensor.dark_sky_humidity
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_wind_speed
      # - sensor.dark_sky_visibility

      - sensor.dark_sky_cloud_coverage_1
      - sensor.dark_sky_daily_high_apparent_temperature_1
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_low_apparent_temperature_1
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_daily_max_precip_intensity_1
      - sensor.dark_sky_humidity_1
      - sensor.dark_sky_precip_1
      - sensor.dark_sky_precip_intensity_1
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_wind_speed_1
      # - sensor.dark_sky_visibility_1